In [5]:
import pandas as pd

df = pd.read_csv('SMSSpamCollection', sep='\t', header=None, names=['label', 'message'])
df

,label,message
0,ham,"Go until jurong point, crazy.. Available only ..."
1,ham,Ok lar... Joking wif u oni...
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...
3,ham,U dun say so early hor... U c already then say...
4,ham,"Nah I don't think he goes to usf, he lives aro..."
...,...,...
5567,spam,This is the 2nd time we have tried 2 contact u...
5568,ham,Will ü b going to esplanade fr home?
5569,ham,"Pity, * was in mood for that. So...any other s..."
5570,ham,The guy did some bitching but I acted like i'd...


In [6]:
# Transform label values to numbers
df['label'] = df.label.map({'ham': 0, 'spam': 1})
df

,label,message
0,0,"Go until jurong point, crazy.. Available only ..."
1,0,Ok lar... Joking wif u oni...
2,1,Free entry in 2 a wkly comp to win FA Cup fina...
3,0,U dun say so early hor... U c already then say...
4,0,"Nah I don't think he goes to usf, he lives aro..."
...,...,...
5567,1,This is the 2nd time we have tried 2 contact u...
5568,0,Will ü b going to esplanade fr home?
5569,0,"Pity, * was in mood for that. So...any other s..."
5570,0,The guy did some bitching but I acted like i'd...


In [7]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df['message'], df['label'])

In [8]:
# Converting Text to numerical data - Bag of words concept
from sklearn.feature_extraction.text import CountVectorizer

vect = CountVectorizer(stop_words='english')

In [18]:
# Train the train dataset
vect.fit(X_train)
X_train_dtm = vect.transform(X_train)

In [19]:
# Transform the test dataset
X_test_dtm = vect.transform(X_test)

In [11]:
# View the feature names (vocabulary)
print("Vocabulary:", vect.get_feature_names_out())
print("Matrix Shape:", X_train_dtm.shape)
print("Matrix (dense format):", X_train_dtm.toarray())

Vocabulary: ['00' '000' '0121' ... 'èn' 'ú1' '〨ud']
Matrix Shape: (4179, 7177)
Matrix (dense format): [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]]


In [12]:
import numpy as np
# Calculate sparsity of the matrix
print("Sparsity:", (1 - (np.count_nonzero(X_train_dtm.toarray()) / X_train_dtm.toarray().size)) * 100, "% of values are zero" )

Sparsity: 99.89110677427558 % of values are zero


In [13]:
from scipy.sparse import csr_matrix

print("Sparse matrix representation:")
print(csr_matrix(X_train_dtm))

Sparse matrix representation:
<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 32660 stored elements and shape (4179, 7177)>
  Coords	Values
  (0, 3879)	1
  (0, 4196)	1
  (0, 5678)	1
  (0, 4865)	1
  (0, 3750)	1
  (0, 6482)	1
  (0, 3445)	1
  (1, 4865)	1
  (1, 6370)	1
  (1, 2593)	1
  (1, 1649)	1
  (1, 2978)	1
  (1, 4060)	1
  (1, 2273)	1
  (2, 3193)	1
  (2, 1131)	1
  (2, 3581)	1
  (2, 3363)	1
  (2, 3234)	1
  (2, 752)	1
  (2, 3908)	1
  (2, 6322)	2
  (2, 6850)	1
  (2, 1639)	1
  (2, 7102)	1
  :	:
  (4175, 4034)	1
  (4175, 1830)	1
  (4175, 4637)	1
  (4175, 6557)	1
  (4176, 2047)	1
  (4176, 6147)	1
  (4177, 5615)	1
  (4177, 3830)	1
  (4178, 3604)	1
  (4178, 6338)	1
  (4178, 2967)	1
  (4178, 7025)	1
  (4178, 1851)	1
  (4178, 5053)	1
  (4178, 1715)	1
  (4178, 2802)	1
  (4178, 2364)	1
  (4178, 1458)	1
  (4178, 1)	1
  (4178, 4199)	1
  (4178, 5195)	1
  (4178, 7097)	1
  (4178, 267)	1
  (4178, 4384)	1
  (4178, 140)	1


In [14]:
from sklearn.naive_bayes import MultinomialNB

# Train the model
nb = MultinomialNB()
nb.fit(X_train_dtm, y_train)

MultinomialNB()

In [20]:
predictions = nb.predict(X_test_dtm)
prediction_list = list(zip(X_test, predictions))
prediction_list

[('Life is more strict than teacher... Bcoz Teacher teaches lesson &amp; then conducts exam, But Life first conducts Exam &amp; then teaches Lessons. Happy morning. . .',
  np.int64(0)),
 ('As usual..iam fine, happy &amp; doing well..:)', np.int64(0)),
 ('Just wait till end of march when el nino gets himself. Oh.', np.int64(0)),
 ("alright. Thanks for the advice. Enjoy your night out. I'ma try to get some sleep...",
  np.int64(0)),
 ('Good afternoon sexy buns! How goes the job search ? I wake and you are my first thought as always, my love. I wish your fine and happy and know I adore you!',
  np.int64(0)),
 ('I cant pick the phone right now. Pls send a message', np.int64(0)),
 ('I reach home safe n sound liao...', np.int64(0)),
 ('Hey cutie. How goes it? Here in WALES its kinda ok. There is like hills and shit but i still avent killed myself. ',
  np.int64(0)),
 ('Hi mom we might be back later than  &lt;#&gt; ', np.int64(0)),
 ("She said,'' do u mind if I go into the bedroom for a minu

In [21]:
# Evaluating the model
from sklearn import metrics

print("Accuracy:", metrics.accuracy_score(y_test, predictions))
print("Confusion matrix:\n", metrics.confusion_matrix(y_test, predictions))
print("Classification report:\n", metrics.classification_report(y_test, predictions))

Accuracy: 0.9856424982053122
Confusion matrix:
 [[1202    6]
 [  14  171]]
Classification report:
               precision    recall  f1-score   support

           0       0.99      1.00      0.99      1208
           1       0.97      0.92      0.94       185

    accuracy                           0.99      1393
   macro avg       0.98      0.96      0.97      1393
weighted avg       0.99      0.99      0.99      1393



In [22]:
# Make predictions on random messages
random_messages = ["You've Won!", "Hi, how are you?", "The IRS is Trying to Contact You",
                   "You Have a Refund Coming", "Verify Your Bank Account", "Love is in the air!",
                   "You Have a Package Delivery", "Boss Needs Help!", "A Family Member Needs Help",
                   "Are you up to go cinema?", "Let's go swimming"]
random_messages_dtm = vect.transform(random_messages)
predictions = nb.predict(random_messages_dtm)
prediction_list = list(zip(random_messages, predictions))
prediction_list

[("You've Won!", np.int64(0)),
 ('Hi, how are you?', np.int64(0)),
 ('The IRS is Trying to Contact You', np.int64(1)),
 ('You Have a Refund Coming', np.int64(0)),
 ('Verify Your Bank Account', np.int64(0)),
 ('Love is in the air!', np.int64(0)),
 ('You Have a Package Delivery', np.int64(1)),
 ('Boss Needs Help!', np.int64(0)),
 ('A Family Member Needs Help', np.int64(0)),
 ('Are you up to go cinema?', np.int64(0)),
 ("Let's go swimming", np.int64(0))]

In [23]:
right_answers = [1,0,1,1,1,0,1,1,1,0,0]
print("Accuracy:", metrics.accuracy_score(right_answers, predictions))
print("Confusion matrix:\n", metrics.confusion_matrix(right_answers, predictions))
print("Classification report:\n", metrics.classification_report(right_answers, predictions))

Accuracy: 0.5454545454545454
Confusion matrix:
 [[4 0]
 [5 2]]
Classification report:
               precision    recall  f1-score   support

           0       0.44      1.00      0.62         4
           1       1.00      0.29      0.44         7

    accuracy                           0.55        11
   macro avg       0.72      0.64      0.53        11
weighted avg       0.80      0.55      0.51        11



In [27]:
sms = input("Enter a message: ")
sms_dtm = vect.transform([sms])
prediction = nb.predict(sms_dtm)
if prediction[0] == 1:
    print("Spam")
else:
    print("Not spam")

Enter a message: fgsdufgeurfgukert
Not spam
